apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-registry-cache
  labels:
    app: registry-cache
    release: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 443
  selector:
    app: registry-cache
    release: {{ .Release.Name }}
