{{- if .Values.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-tracer-bot
  labels:
    app: tracer-bot
spec:
  replicas: {{ .Values.replicaCount | default 1 }}
  selector:
    matchLabels:
      app: tracer-bot
  template:
    metadata:
      labels:
        app: tracer-bot
    spec:
      {{- include "buttercup.imagePullSecrets" . | nindent 6 }}
      initContainers:
      {{- include "buttercup.waitForRedis" . | nindent 6 }}
      {{- include "buttercup.waitForDocker" . | nindent 6 }}
      containers:
      - name: tracer-bot
        image: "{{ .Values.global.fuzzerImage.repository }}:{{ .Values.global.fuzzerImage.tag }}"
        imagePullPolicy: {{ .Values.global.fuzzerImage.pullPolicy }}
        command: ["buttercup-tracer-bot", "--wdir", "{{ include "buttercup.nodeLocalCrsScratchPath" . }}", "--redis_url", "{{ include "buttercup.core.redisUrl" . }}"]
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
        livenessProbe:
          exec:
            command: {{- include "buttercup.healthCheck" (dict "maxStaleTime" .Values.healthCheck.maxStaleTime) | nindent 14 }}
          initialDelaySeconds: {{ .Values.healthCheck.initialDelaySeconds | default 60 }}
          periodSeconds: {{ .Values.healthCheck.periodSeconds | default 300 }}
          timeoutSeconds: {{ .Values.healthCheck.timeoutSeconds | default 10 }}
          failureThreshold: {{ .Values.healthCheck.failureThreshold | default 2 }}
        volumeMounts:
        {{- include "buttercup.standardVolumeMounts" (dict "usesTasksStorage" true) | nindent 8 }}
        {{- include "buttercup.nodeLocalVolumeMount" . | nindent 8 }}
        {{- include "buttercup.dockerSocketVolumeMount" . | nindent 8 }}
        env:
        {{- include "buttercup.commonEnv" . | nindent 8 }}
        {{- include "buttercup.env.dockerSocket" . | nindent 8 }}
        {{- include "buttercup.env.nodeData" . | nindent 8 }}
        {{- include "buttercup.env.telemetry" . | nindent 8 }}
      volumes:
      {{- include "buttercup.volumes.scratch" . | nindent 6 }}
      {{- include "buttercup.volumes.tasks" . | nindent 6 }}
      {{- include "buttercup.dockerSocketVolume" . | nindent 6 }}
      {{- include "buttercup.nodeLocalVolume" . | nindent 6 }}
{{- end }}
