apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-task-server
  labels:
    app: task-server
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  # Set type based on environment
  type: ClusterIP
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.port }}
      protocol: TCP
      name: http
  selector:
    app: task-server
