apiVersion: v1
kind: Secret
metadata:
  name: ghcr-auth
data:
  {{- $secret := (lookup "v1" "Secret" .Release.Namespace "ghcr") | default dict }}
  {{- $username := get (get $secret "data") "username" | default "" | b64dec }}
  {{- $pat := get (get $secret "data") "pat" | default "" | b64dec }}
  .dockerconfigjson: {{ printf "{\"auths\":{\"ghcr.io\":{\"auth\":\"%s\"}}}" (printf "%s:%s" $username $pat | b64enc) | b64enc }}
type: kubernetes.io/dockerconfigjson
